### ISSUE TITLE
"Security certificate expired"

### ISSUE THREAD

**Issue by neroist** [webui-dev/website#17]
When trying to connect to https://webui.me, it shows this error:
Chrome
![image](https://github.com/webui-dev/website/assets/71654487/dd07d3fd-5234-46c0-ac92-d2c06fde0e4a)
Firefox
![image](https://github.com/webui-dev/website/assets/71654487/b115d386-6bf1-48b7-8bc8-89e91a52adf0)

**Comment by jinzhongjia** [comment]
Maybe, we can just use github page?
It's simpler and doesn't require an additional server

**Comment by Sosiaka** [comment]
Same. If u dont have free ssl cert or u cant ger it, use http, not https
